// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX7PCdIpNTZAYXi6viASwt_4qS9znpQYY',
    appId: '1:734479508053:web:d49266f8edb0b00c5daadc',
    messagingSenderId: '734479508053',
    projectId: 'mapzzz-62a4f',
    authDomain: 'mapzzz-62a4f.firebaseapp.com',
    storageBucket: 'mapzzz-62a4f.firebasestorage.app',
    measurementId: 'G-2VJXH4VKLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAou4aPcGMlsl_l5pGogFB4B9Z9Oq03tzw',
    appId: '1:734479508053:android:92fcf0cc0302f8a35daadc',
    messagingSenderId: '734479508053',
    projectId: 'mapzzz-62a4f',
    storageBucket: 'mapzzz-62a4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFus7h1t_wwZ2-w0ZwqSiulWJ4RlS37U',
    appId: '1:734479508053:ios:84788005c2e616875daadc',
    messagingSenderId: '734479508053',
    projectId: 'mapzzz-62a4f',
    storageBucket: 'mapzzz-62a4f.firebasestorage.app',
    iosBundleId: 'com.example.authBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBFus7h1t_wwZ2-w0ZwqSiulWJ4RlS37U',
    appId: '1:734479508053:ios:84788005c2e616875daadc',
    messagingSenderId: '734479508053',
    projectId: 'mapzzz-62a4f',
    storageBucket: 'mapzzz-62a4f.firebasestorage.app',
    iosBundleId: 'com.example.authBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX7PCdIpNTZAYXi6viASwt_4qS9znpQYY',
    appId: '1:734479508053:web:e6bf134dfdb033a95daadc',
    messagingSenderId: '734479508053',
    projectId: 'mapzzz-62a4f',
    authDomain: 'mapzzz-62a4f.firebaseapp.com',
    storageBucket: 'mapzzz-62a4f.firebasestorage.app',
    measurementId: 'G-07LZMHE6GL',
  );
}
